### PR TITLE
Fix quick-start to work with OCP v4.9 

### PR DESCRIPTION
**Pull request by pmacik**
The current quickstart assumes and uses old version of Crunchy Postgres operator (`v4.7.0`) which fails to install to OpenShift v4.9 (due to use of unsupported CRD api `v1beta1`)

Thist PR:
 * Updates the quick-start to use the latest version of the Crunchy Postgres operator (`v5`) that works on both 4.8 and 4.9
 * Includes verification steps including commands and expected output

### CODE REVIEW

**Review by slemeur — APPROVED** [review]
Thanks @pmacik !!

**Review by Srivaralakshmi — COMMENTED** [review]
Thank you @pmacik for adding the necessary information.

As discussed, request you to provide the verification steps/commands with example snippets as necessary, for each of the steps in all these procedures. Some steps do mention the verification information, but it is good to include the commands and examples :)

**Comment by pmacik** [comment]
@Srivaralakshmi I've added the verification steps including the commands/snippets as well as the expected output

**Review by baijum — APPROVED** [review]
LGTM

**Review by Srivaralakshmi — COMMENTED** [review]
@baijum @pmacik 

This prerequisite is missing. Please add it:

- You have installed PostgreSQL `psql` CLI.

Thanks!

**Pull request merged**
